@Library("shared") _
pipeline {
    agent { label "vinod" }
    
    stages {
        stage("Hello") {
            steps {
                script {
                    hello()
                }
            }
        }
        stage("Code") {
            steps {
                script {
                    clone("https://github.com/akash8992/django-notes-app.git", "main")
                }
            }
        }
        stage("Build") {
            steps {
                echo "This is building the code"
                sh "docker build -t django-todo-cicd:latest ."
            }
        }
        stage("Push to DockerHub") {
            steps {
                echo "This is pushing image to Docker Hub"
                withCredentials([usernamePassword(
                    credentialsId: "dockerhub-cred", 
                    passwordVariable: "dockerHubPass", 
                    usernameVariable: "dockerHubUser"
                )]) {
                    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
                    sh "docker image tag django-todo-cicd:latest akash8992/django-todo-cicd:latest"
                    sh "docker push akash8992/django-todo-cicd:latest"
                }
            }
        }
        stage("Deploy") {
            steps {
                echo "This is deploying the code"
                // Uncomment the following line if you want to run the container
                // sh "docker run -d -p 8000:8000 django-todo-cicd:latest"
                sh "docker compose up -d"
            }
        }
    }
}
